module.exports = {
  MF: {
    apartment: {
      'air conditioning': { variants: ['air conditioner', 'ac'] },
      'cable included': { variants: ['cable'] },
      'custom cabinetry': { variants: ['custom cab'] },
      'dishwasher': { variants: ['dish washer', 'dishwashing machine', 'dishwashing', 'dishwashing machine', 'dishwashing', 'dishwashing machine'] },
      'energy-efficient appliances': { variants: ['energy efficient utilities', 'energy efficient appliances'] },
      'fireplace': { variants: [] },
      'garages available': { variants: ['garage'] },
      'granite counters': { variants: [] },
      'hardwood flooring': { variants: [] },
      'high ceilings': { variants: ['highceilings', 'high ceiling'] },
      'high speed internet access': { variants: ['high speed internet'] },
      'private balcony': { variants: [] },
      'private patio': { variants: [] },
      'soundproof walls': { variants: [] },
      'stainless-steel appliances': { variants: [] },
      'vaulted ceilings': { variants: [] },
      'walk-in closet': { variants: ['walk in closets'] },
      'washer/dryer connections': { variants: ['washer and dryer connections', 'washer dryer'] },
      'wood-style flooring': { variants: ['hardwood-style floors'] }
    },
    community: {
      'basketball court': { variants: [] },
      'community garden': { variants: [] },
      'business center': { variants: [] },
      'close to dog park': { variants: [] },
      'gated electronic entrance': { variants: [] },
      'laundry facility': { variants: ['laundry'] },
      'carport parking available': { variants: [] },
      'close to park': { variants: [] },
      'clubhouse': { variants: [] },
      'fitness center': { variants: ['gym'] },
      'furnished aparments available': { variants: ['furnished'] },
      'on-site dog park': { variants: ['onsite dog park'] },
      'online rental payments': { variants: [] },
      'onsite management': { variants: [] },
      'playground': { variants: [] },
      'recycling center': { variants: [] },
      'spa': { variants: ['hottub', 'hot tub'] },
      'swimming pool': { variants: [] },
      'tennis court': { variants: [] },
      'volleyball court': { variants: [] },
      'wifi available': { variants: [] },
    }
  },
  SL: {
    'In-Home/Unit Features': {
      'Move-In Assistance': { variants: ['move-in assistance'] },
      'LEED Certified': { variants: [] },
      'Other Green Initiatives': { variants: [] },
      'Air Conditioning': { variants: ['air conditioner', 'ac'] },
      'Cable Included': { variants: ['cable'] },
      'WiFi Available': { variants: [] },
      'Ceiling Fans': { variants: [] },
      'Custom Lighting': { variants: [] },
      'Full Kitchen': { variants: [] },
      'Kitchenette': { variants: [] },
      'Kitchen Island or Bar': { variants: [] },
      'Granite Counters': { variants: [] },
      'Custom Cabinetry': { variants: ['custom cab'] },
      'Energy-Efficient Appliances': { variants: ['energy efficient utilities', 'energy efficient appliances'] },
      'Stainless-Steel Appliances': { variants: [] },
      'Refrigerator': { variants: ['refrigerator', 'fridge'] },
      'Dishwasher': { variants: ['dish washer', 'dishwashing machine', 'dishwashing', 'dishwashing machine', 'dishwashing', 'dishwashing machine'] },
      'Microwave': { variants: ['microwave', 'microwave oven'] },
      'Garbage Disposal': { variants: ['garbage disposal', 'garbage', 'garbage can', 'garbage bin'] },
      'Utilities Included': { variants: ['utilities'] },
      'Weekly Housekeeping': { variants: [] },
      'Washer/Dryer Connections': { variants: ['washer and dryer connections', 'washer dryer'] },
      'In-Home Washer/Dryer': { variants: ['in-home washer and dryer'] },
      'Trash Service': { variants: [] },
      'Laundry Service': { variants: ['laundry'] },
      'Walk-In Closets': { variants: ['walk in closets'] },
      'Fireplace': { variants: [] },
      'Curtains or Blinds Included': { variants: [] },
      'Hardwood Floors': { variants: [] },
      'Hardwood-Style Floors': { variants: ['hardwood-style floors'] },
      'High Ceilings': { variants: ['highceilings', 'high ceiling'] },
      'Vaulted Ceilings': { variants: [] },
      'Cathedral Ceilings': { variants: [] },
      'Private Balcony': { variants: [] },
      'private Patio': { variants: [] },
      'Smoke Free': { variants: [] },
      'Additional Storage': { variants: [] }
    },
    community: {
      'Gated Electronic Entrance': { variants: [] },
      'Parking Garage': { variants: [] },
      'Covered Parking': { variants: [] },
      'Private Garages Available': { variants: ['garage'] },
      'Transportation Services': { variants: [] },
      'Restaurant-Style Dining': { variants: [] },
      'In-Room Dining': { variants: [] },
      'Personal Care': { variants: [] },
      'Clubhouse': { variants: [] },
      'Fitness Center': { variants: ['gym'] },
      'Yoga/ Pilates Studio': { variants: [] },
      'Swimming Pool': { variants: [] },
      'Spa/Hot Tub': { variants: ['hottub', 'hot tub'] },
      'Cabanas': { variants: [] },
      'Fitness Classes': { variants: [] },
      'Outdoor Grilling/BBQ Stations': { variants: [] },
      'Playground': { variants: [] },
      'Basketball': { variants: [] },
      'Volleyball': { variants: [] },
      'Tennis Courts': { variants: [] },
      'Laundry Facilities On-Site': { variants: ['laundry'] },
      'Recycling Center': { variants: [] },
      '24-Hour Emergency Maintenance': { variants: [] },
      'Walking Trails on or near Property': { variants: [] },
      'Close to Parks': { variants: [] },
      'Close to Dog Park': { variants: [] },
      'On-Site Dog Park': { variants: ['onsite dog park'] },
      'Pet Friendly': { variants: [] },
      'Cat Friendly': { variants: [] },
      'Dog Friendly': { variants: [] }
    }
  },
  SS: {
    'facility features': {
      'climate controlled': { variants: ['climate control'] },
      'free moving truck': { variants: ['moving truck', 'moving truck available to rent'] },
      'groud floor units': { variants: [] },
      'rv & car storage': { variants: [] },
      'package delivery': { variants: [] },
      'online bill payment': { variants: [] },
      'month to month': { variants: [] },
      'military discounts': { variants: [] },
      'free truck use': { variants: [] },
      'onsite manager': { variants: ['on-site manager'] },
      'free dolly & cart use':  { variants: [] }
    },
    'storage types': {
      'automobile storage': { variants: [] },
      'boat storage': { variants: [] },
      'business and/or commercial storage': { variants: ['commercial storage'] },
      'cold storage facility': { variants: [] },
      'ground-level units': { variants: [] },
      'indoor storage': { variants: [] },
      'motorcycle storage': { variants: [] },
      'outdoor storage': { variants: [] },
      'pod storage': { variants: [] },
      'record storage facility': { variants: [] },
      'rv storage': { variants: [] },
      'storage locker rental': { variants: [] },
      'temperature controlled storage': { variants: [] },
      'warehouse': { variants: [] },
      'wine storage': { variants: [] }
    }
  }
}
